LibraryMVC/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.DAL;
using LibraryMVC.Models;
using LibraryMVC.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using System.Net.Mail;

namespace LibraryMVC.Controllers
{
    [Authorize(Roles = "Reader, Admin, Employee")]
    public class BookController : Controller
    {
        private ApplicationDbContext db;
        protected UserManager<ApplicationUser> UserManager;

        public BookController()
        {
            this.db = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }

        // GET: Book
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //[HttpPost]
        public ActionResult AddToQueue(int id)
        {
            Book book = db.Books.Where(b => b.Id == id).FirstOrDefault();

            var user = UserManager.FindById(User.Identity.GetUserId());

            var queue = new Queue();
            queue.Book = book;
            queue.User = user;

            book.Queues.Add(queue);
            db.SaveChanges();


            TempData["Success"] = "Added Successfully!";
            return RedirectToAction("Index");
        }

        public ActionResult Filters(string title, string author, string isbn)
        {
            var model = db.Books.AsQueryable();
            if (!string.IsNullOrEmpty(title))
            {
                model = model.Where(a => a.Title.ToLower().Equals(title.ToLower()));
            }
            if (!string.IsNullOrEmpty(author))
            {
                model = model.Where(a => a.Author.ToLower().Equals(author.ToLower()));
            }
            if (!string.IsNullOrEmpty(isbn))
            {
                model = model.Where(a => a.ISBN.ToLower().Equals(isbn.ToLower()));
            }
            
            return View("Search", model.ToList());
        }
        
        public ActionResult SaveHisotry()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SearchCategory()
        {
            ViewBag.MainCategories = new SelectList(db.Categories, "Id", "Name");
            if (TempData["List"] != null)
            {
                return View(TempData["List"]);
            }
            var model = db.Books.ToList();
             return View(model);
        }

        [HttpPost]
        public ActionResult SearchCategory(int categories)
        {
            List<Book> ListBook = new List<Book>();

            var model = db.Books.Where(a => a.Category.Id == categories).FirstOrDefault();

            ListBook = FindBookRootID(categories, ListBook);

            ListBook.Add(model);
            TempData["List"] = ListBook;
            return RedirectToAction("SearchCategory");
        }

        public List<Book> FindBookRootID(int rootId, List<Book> ListBook)
        {
            var model = db.Books.Where(a => a.Category.RootCategoryId == rootId).FirstOrDefault();
            if (model != null)
            {
                ListBook.Add(model);
                return FindBookRootID(model.Category.Id, ListBook);
            }

                return ListBook;
            
        }

        [HttpGet]
        public ActionResult SearchByTag()
        {
            ViewBag.Tags = new SelectList(db.BookTags, "Id", "Text");
            if (TempData["BookList"] != null)
            {
                return View(TempData["BookList"]);
            }
            var model = db.Books.ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult SearchByTag(int BookTags)
        {
            var model = db.BookTags.Where(a => a.Id == BookTags).First();
            List<Book> ListBook = new List<Book>();
            foreach(Book b in db.Books)
            {
                foreach (BookTag bookTag in b.BookTags)
                {
                    if (bookTag.Id == BookTags)
                    {
                        ListBook.Add(b);
                    }
                }
            }

            TempData["BookList"] = ListBook;
            return RedirectToAction("SearchByTag");
        }

        [HttpGet]
        public ActionResult ReturnBook()
        {
            List<Book> ListBook = new List<Book>();
            string id = User.Identity.GetUserId();
            var model = db.Borrows.Where(a => a.User.Id == id).ToList();
            foreach (Lend L in model)
            {
                ListBook.Add(L.Book);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> ReturnBook(int id)
        {
            var modelLend = db.Borrows.Where(a => a.Book.Id == id).First();
            var modelBook = db.Books.Where(a => a.Id == id).First();
            modelBook.Available = true;
            modelLend.DateReturn = DateTime.Now;
            modelLend.State = "Returned";
            var modelQueue = db.Queues.Where(a => a.Book.Id == id).FirstOrDefault();
            if (modelQueue != null)
            {
                Lend lendBook = new Lend();
                lendBook.User = modelQueue.User;
                lendBook.Book = modelBook;
                lendBook.State = "Waiting For akcept by user";
                modelBook.Available = false;

                // Send mail to user
                var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                var message = new MailMessage();
                message.To.Add(new MailAddress(modelQueue.User.Email));  // replace with valid value 
                message.From = new MailAddress("mailtomvc@gmail.com");  // replace with valid value
                message.Subject = "Book is already available";
                message.Body = string.Format(body, "Library", "mailtomvc@gmail.com", "Book is already available");
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    await smtp.SendMailAsync(message);
                }

                db.Queues.Remove(modelQueue);
                db.Borrows.Add(lendBook);
                //modelBook.Available = false;
            }

            db.Borrows.Remove(modelLend);
            db.SaveChanges();
            return RedirectToAction("ReturnBook");
        }

        [HttpGet]
        public ActionResult Queue()
        {
            List<Book> ListBook = new List<Book>();
            string id = UserManager.FindById(User.Identity.GetUserId()).Id;
            var model = db.Queues.Where(a => a.User.Id == id).ToList();

            foreach (Queue q in model)
            {   
                ListBook.Add(q.Book);
            }

            return View(ListBook);
        }
        [HttpGet]
        public ActionResult BookWaitingOnUser()
        {
            List<Lend> LendBook = new List<Lend>();
            string idUser = UserManager.FindById(User.Identity.GetUserId()).Id;
            var model = db.Borrows.Where(a => a.User.Id == idUser).ToList();
            foreach (Lend l in model)
            {
                if (l.State == "Waiting For akcept by user")
                {
                    LendBook.Add(l);
                }
            }
            return View(LendBook);
        }
        [HttpPost]
        public ActionResult BookWaitingOnUser(int id)
        {
            string idUser = UserManager.FindById(User.Identity.GetUserId()).Id;
            var model = db.Borrows.Where(a => a.User.Id == idUser).ToList();
            foreach (Lend l in model)
            {
                if (l.Id == id)
                {
                    l.Book.Available = false;
                    l.DateBorrowed = DateTime.Now;
                    l.DateReturn = DateTime.Now.AddDays(7);
                    l.State = "Borrowed";
                    db.SaveChanges();
                }
            }


            return RedirectToAction("BookWaitingOnUser");
        }



    }
}

LibraryMVC/Controllers/LendController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.DAL;
using LibraryMVC.Models;

namespace LibraryMVC.Controllers
{
    [Authorize(Roles ="Employee")]
    public class LendController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Lend
        public ActionResult Index()
        {
            return View(db.Borrows.ToList());
        }

        // GET: Lend/Create
        public ActionResult Create()
        {
            var roleId = db.Roles.Where(r => r.Name == "Reader").FirstOrDefault().Id;

            ViewBag.Readers = new SelectList(db.Users.Where(u => u.Roles.Where(r => r.RoleId == roleId).Any()).ToList(), "Id", "Email");
            ViewBag.Books = new SelectList(db.Books.Where(b => b.Available == true).ToList(), "Id", "Title");
            return View();
        }

        // POST: Lend/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DateBorrowed,DateReturn,State")] Lend lend)
        {
            if (ModelState.IsValid)
            {
                db.Borrows.Add(lend);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lend);
        }

        // GET: Lend/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lend lend = db.Borrows.Find(id);
            if (lend == null)
            {
                return HttpNotFound();
            }
            return View(lend);
        }

        // POST: Lend/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DateBorrowed,DateReturn,State")] Lend lend)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lend).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lend);
        }

        // GET: Lend/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lend lend = db.Borrows.Find(id);
            if (lend == null)
            {
                return HttpNotFound();
            }
            return View(lend);
        }

        // POST: Lend/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lend lend = db.Borrows.Find(id);
            lend.Book.Available = true;
            db.Borrows.Remove(lend);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryMVC/Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.DAL;
using LibraryMVC.Models;

namespace LibraryMVC.Controllers
{
    public class NewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: New
        public ActionResult Index()
        {
            return View(db.News.ToList());
        }

        // GET: New/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // GET: New/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: New/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Text")] New @new)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(@new);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@new);
        }

        // GET: New/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // POST: New/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Text")] New @new)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@new).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@new);
        }

        // GET: New/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // POST: New/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            New @new = db.News.Find(id);
            db.News.Remove(@new);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Library</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @if (IsSectionDefined("AddToHead"))
    {
        @RenderSection("AddToHead", required: false)
    }

    @RenderSection("AddToHeadAnotherWay", required: false)

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<style>
    @RenderSection("styles", false)
    </style>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Books
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("All Books", "Index", "BookManage")</li>
                                    <li>@Html.ActionLink("Search by category", "SearchCategory", "Book")</li>
                                    <li>@Html.ActionLink("Seach by tag", "SearchByTag", "Book")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Employees", "Index", "Employee")</li>
                            <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                            <li>@Html.ActionLink("BookTags", "Index", "BookTag")</li>
                            <li>@Html.ActionLink("Create News", "Index", "New")</li>
                            @*<li>@Html.ActionLink("Lends", "Index", "Lend")</li>*@

                        }
                        if (User.IsInRole("Employee"))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Books
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("All Books", "Index", "BookManage")</li>
                                    <li>@Html.ActionLink("Search by category", "SearchCategory", "Book")</li>
                                    <li>@Html.ActionLink("Seach by tag", "SearchByTag", "Book")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Readers", "Index", "Reader")</li>
                            <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                            <li>@Html.ActionLink("BookTags", "Index", "BookTag")</li>
                            <li>@Html.ActionLink("Lends", "Index", "Lend")</li>

                        }
                        if (User.IsInRole("Reader"))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Books
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("All Books", "Index", "Book")</li>
                                    <li>@Html.ActionLink("Search by category", "SearchCategory", "Book")</li>
                                    <li>@Html.ActionLink("Seach by tag", "SearchByTag", "Book")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Your Cart", "ShowCart", "Cart")</li>
                            <li>@Html.ActionLink("Your Queues", "Queue", "Book")</li>
                            <li>@Html.ActionLink("To Lend", "BookWaitingOnUser", "Book")</li>
                            <li>@Html.ActionLink("Return book", "ReturnBook", "Book")</li>

                            @*<li>@Html.ActionLink("Lends", "Index", "Lend")</li>*@

                        }

                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Library. Created by Michał Gil & Kamil Oleksy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>