LibraryMVC/Models/BookTag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryMVC.Models
{
    public class BookTag
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public virtual ICollection<Book> Books { get; set; }
    }
}

LibraryMVC/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.DAL;
using LibraryMVC.Models;
using LibraryMVC.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using System.Net.Mail;

namespace LibraryMVC.Controllers
{
    [Authorize(Roles = "Reader, Admin, Employee")]
    public class BookController : Controller
    {
        private ApplicationDbContext db;
        protected UserManager<ApplicationUser> UserManager;

        public BookController()
        {
            this.db = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }

        // GET: Book
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //[HttpPost]
        public ActionResult AddToQueue(int id)
        {
            Book book = db.Books.Where(b => b.Id == id).FirstOrDefault();

            var user = UserManager.FindById(User.Identity.GetUserId());

            var queue = new Queue();
            queue.Book = book;
            queue.User = user;

            book.Queues.Add(queue);
            db.SaveChanges();


            TempData["Success"] = "Added Successfully!";
            return RedirectToAction("Index");
        }

        public ActionResult Filters(string title, string author, string isbn)
        {
            var model = db.Books.AsQueryable();
            if (!string.IsNullOrEmpty(title))
            {
                model = model.Where(a => a.Title.ToLower().Equals(title.ToLower()));
            }
            if (!string.IsNullOrEmpty(author))
            {
                model = model.Where(a => a.Author.ToLower().Equals(author.ToLower()));
            }
            if (!string.IsNullOrEmpty(isbn))
            {
                model = model.Where(a => a.ISBN.ToLower().Equals(isbn.ToLower()));
            }
            
            return View("Search", model.ToList());
        }
        
        public ActionResult SaveHisotry()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SearchCategory()
        {
            ViewBag.MainCategories = new SelectList(db.Categories, "Id", "Name");
            if (TempData["List"] != null)
            {
                return View(TempData["List"]);
            }
            var model = db.Books.ToList();
             return View(model);
        }

        [HttpPost]
        public ActionResult SearchCategory(int categories)
        {
            List<Book> ListBook = new List<Book>();

            var model = db.Books.Where(a => a.Category.Id == categories).FirstOrDefault();

            ListBook = FindBookRootID(categories, ListBook);

            ListBook.Add(model);
            TempData["List"] = ListBook;
            return RedirectToAction("SearchCategory");
        }

        public List<Book> FindBookRootID(int rootId, List<Book> ListBook)
        {
            var model = db.Books.Where(a => a.Category.RootCategoryId == rootId).FirstOrDefault();
            if (model != null)
            {
                ListBook.Add(model);
                return FindBookRootID(model.Category.Id, ListBook);
            }

                return ListBook;
            
        }

        [HttpGet]
        public ActionResult SearchByTag()
        {
            ViewBag.Tags = new SelectList(db.BookTags, "Id", "Text");
            if (TempData["BookList"] != null)
            {
                return View(TempData["BookList"]);
            }
            var model = db.Books.ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult SearchByTag(int BookTags)
        {
            var model = db.BookTags.Where(a => a.Id == BookTags).First();
            List<Book> ListBook = new List<Book>();
            foreach(Book b in db.Books)
            {
                foreach (BookTag bookTag in b.BookTags)
                {
                    if (bookTag.Id == BookTags)
                    {
                        ListBook.Add(b);
                    }
                }
            }

            TempData["BookList"] = ListBook;
            return RedirectToAction("SearchByTag");
        }

        [HttpGet]
        public ActionResult ReturnBook()
        {
            List<Book> ListBook = new List<Book>();
            string id = User.Identity.GetUserId();
            var model = db.Borrows.Where(a => a.User.Id == id).ToList();
            foreach (Lend L in model)
            {
                ListBook.Add(L.Book);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> ReturnBook(int id)
        {
            var modelLend = db.Borrows.Where(a => a.Book.Id == id).First();
            var modelBook = db.Books.Where(a => a.Id == id).First();
            modelBook.Available = true;
            modelLend.DateReturn = DateTime.Now;
            modelLend.State = "Returned";
            var modelQueue = db.Queues.Where(a => a.Book.Id == id).FirstOrDefault();
            if (modelQueue != null)
            {
                Lend lendBook = new Lend();
                lendBook.User = modelQueue.User;
                lendBook.Book = modelBook;
                lendBook.State = "Waiting For akcept by user";
                modelBook.Available = false;

                // Send mail to user
                var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                var message = new MailMessage();
                message.To.Add(new MailAddress(modelQueue.User.Email));  // replace with valid value 
                message.From = new MailAddress("mailtomvc@gmail.com");  // replace with valid value
                message.Subject = "Book is already available";
                message.Body = string.Format(body, "Library", "mailtomvc@gmail.com", "Book is already available");
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    await smtp.SendMailAsync(message);
                }

                db.Queues.Remove(modelQueue);
                db.Borrows.Add(lendBook);
                //modelBook.Available = false;
            }

            db.Borrows.Remove(modelLend);
            db.SaveChanges();
            return RedirectToAction("ReturnBook");
        }

        [HttpGet]
        public ActionResult Queue()
        {
            List<Book> ListBook = new List<Book>();
            string id = UserManager.FindById(User.Identity.GetUserId()).Id;
            var model = db.Queues.Where(a => a.User.Id == id).ToList();

            foreach (Queue q in model)
            {   
                ListBook.Add(q.Book);
            }

            return View(ListBook);
        }
        [HttpGet]
        public ActionResult BookWaitingOnUser()
        {
            List<Lend> LendBook = new List<Lend>();
            string idUser = UserManager.FindById(User.Identity.GetUserId()).Id;
            var model = db.Borrows.Where(a => a.User.Id == idUser).ToList();
            foreach (Lend l in model)
            {
                if (l.State == "Waiting For akcept by user")
                {
                    LendBook.Add(l);
                }
            }
            return View(LendBook);
        }
        [HttpPost]
        public ActionResult BookWaitingOnUser(int id)
        {
            string idUser = UserManager.FindById(User.Identity.GetUserId()).Id;
            var model = db.Borrows.Where(a => a.User.Id == idUser).ToList();
            foreach (Lend l in model)
            {
                if (l.Id == id)
                {
                    l.Book.Available = false;
                    l.DateBorrowed = DateTime.Now;
                    l.DateReturn = DateTime.Now.AddDays(7);
                    l.State = "Borrowed";
                    db.SaveChanges();
                }
            }


            return RedirectToAction("BookWaitingOnUser");
        }



    }
}

LibraryMVC/Controllers/BookManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.DAL;
using LibraryMVC.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace LibraryMVC.Controllers
{
    [Authorize(Roles = "Admin, Employee")]
    public class BookManageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        protected UserManager<ApplicationUser> UserManager;

        public BookManageController()
        {
            this.db = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }

        // GET: BookManage
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }
    
        // GET: BookManage/Create
        public ActionResult Create()
        {
            ViewBag.Categories = new SelectList(db.Categories, "Id", "Name");
            ViewBag.BookTags = new MultiSelectList(db.BookTags, "Id", "Text");
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Author,ISBN")] Book book, int categories)
        {
            if (ModelState.IsValid)
            {
                var model = db.Categories.Where(a => a.Id == categories).FirstOrDefault();
                book.Category = model;
                book.Available = true;
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: BookManage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: BookManage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Author,ISBN,Available")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: BookManage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: BookManage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Filters(string title, string author, string isbn)
        {
            var model = db.Books.AsQueryable();
            if (!string.IsNullOrEmpty(title))
            {
                model = model.Where(a => a.Title.ToLower().Equals(title.ToLower()));
            }
            if (!string.IsNullOrEmpty(author))
            {
                model = model.Where(a => a.Author.ToLower().Equals(author.ToLower()));
            }
            if (!string.IsNullOrEmpty(isbn))
            {
                model = model.Where(a => a.ISBN.ToLower().Equals(isbn.ToLower()));
            }


            return View("Search", model.ToList());
        }

        [HttpGet]
        public ActionResult Search(List<Book> SearchList)
        {
            return View(SearchList);
        }
        [HttpGet]
        public ActionResult BookTag(int id)
        {
            ViewBag.Tags = new SelectList(db.BookTags, "Id", "Text");
            TempData["Bookid"] = id;
            var model = db.Books.Where(a => a.Id == id).First();
            return View(model);
        }
        [HttpPost]
        public ActionResult BoogTag(int Tags, int bookId)
        {
            var model = db.Books.Where(a => a.Id == bookId).First();
            var tag = db.BookTags.Where(a => a.Id == Tags).First();
            model.BookTags.Add(tag);
            db.SaveChanges();
            
            return RedirectToAction("Index");
        }

    }
}

LibraryMVC/Controllers/BookTagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMVC.DAL;
using LibraryMVC.Models;

namespace LibraryMVC.Controllers
{
    public class BookTagController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BookTag
        public ActionResult Index()
        {
            return View(db.BookTags.ToList());
        }

        // GET: BookTag/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookTag bookTag = db.BookTags.Find(id);
            if (bookTag == null)
            {
                return HttpNotFound();
            }
            return View(bookTag);
        }

        // GET: BookTag/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookTag/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Text")] BookTag bookTag)
        {
            if (ModelState.IsValid)
            {
                db.BookTags.Add(bookTag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bookTag);
        }

        // GET: BookTag/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookTag bookTag = db.BookTags.Find(id);
            if (bookTag == null)
            {
                return HttpNotFound();
            }
            return View(bookTag);
        }

        // POST: BookTag/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Text")] BookTag bookTag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookTag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookTag);
        }

        // GET: BookTag/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookTag bookTag = db.BookTags.Find(id);
            if (bookTag == null)
            {
                return HttpNotFound();
            }
            return View(bookTag);
        }

        // POST: BookTag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookTag bookTag = db.BookTags.Find(id);
            db.BookTags.Remove(bookTag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryMVC/Views/BookManage/BookTag.cshtml
@model LibraryMVC.Models.Book

@{
    ViewBag.Title = "TagBook";
}

<h2>BookTag</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("BoogTag", "BookManage", FormMethod.Post))
{
    @Html.DropDownList("Tags", (IEnumerable<SelectListItem>)ViewBag.Tags, "Select tag", new { @class = "form-control" })
    <input style='display:inline;' type="submit" value="Add" class="btn btn-default" />
    
    @Html.Hidden("bookId", TempData["Bookid"])
}

LibraryMVC/Views/BookManage/Create.cshtml
@model LibraryMVC.Models.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, "From Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Categories", null, "", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookTags, "Tags", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("BookTags", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryMVC/Views/BookManage/Delete.cshtml
@model LibraryMVC.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryMVC/Views/BookManage/Edit.cshtml
@model LibraryMVC.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Available)
                    @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryMVC/Views/BookManage/Index.cshtml
@model IEnumerable<LibraryMVC.Models.Book>

@{
    ViewBag.Title = "Index";
}

<h2>Books</h2><br />

<p>
    @Html.ActionLink("Create New", "Create")
</p><br />

@using (Html.BeginForm("Filters", "Book", FormMethod.Post))
{
    <div class="form-group">
        <label style="display:inline" for="title">Tytuł: </label>
        <input style="display:inline" type="text" name="title" class="form-control" id="title">
        <label style="display:inline" for="author"> Autor: </label>
        <input style="display:inline" type="text" name="author" class="form-control" id="author">
        <label style="display:inline" for="isbn"> ISBN: </label>
        <input style="display:inline" type="text" name="isbn" class="form-control" id="isbn">
        <input style="display:inline" type="submit" value="Szukaj" class="btn btn-default" />
    </div><br />

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Available)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISBN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Available)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("Add tag", "BookTag", new { id = item.Id }) 
                </td>
            </tr>
        }

    </table>
}

LibraryMVC/Views/BookManage/Search.cshtml
@model IEnumerable<LibraryMVC.Models.Book>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>


@using (Html.BeginForm("Search", "Book", FormMethod.Post, new { model = Model }))
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Available)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISBN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Available)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    @if (item.Available == false)
                    {
                        <p style="display:inline"> | @Html.ActionLink("Add to queue", "AddToQueue", "Book", new { id = item.Id }, null) </p>
                    }
                    else
                    {
                        <p style="display:inline"> | @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = item.Id }, null) </p>

                    }
                </td>
            </tr>
        }

    </table>
    <input type="submit" value="Save your search" class="btn btn-default" />
}